### ISSUE TITLE
Issue when playing an audio

### ISSUE THREAD

**Issue by mNadimMat** [alemangui/pizzicato#107]
Hello , 
I am using pizzicato to play background audios.
Audios are located under localhost:2000 and i'm fetching them from localhost:8080.
I'm getting this error 

> jQuery.Deferred exception: this.getRawSourceNode is not a function TypeError: this.getRawSourceNode is not a function
    at o.Sound.value [as getSourceNode] (https://cdnjs.cloudflare.com/ajax/libs/pizzicato/0.6.4/Pizzicato.min.js:1:11110)
    at o.Sound.value [as play] (https://cdnjs.cloudflare.com/ajax/libs/pizzicato/0.6.4/Pizzicato.min.js:1:7601)
    at playAudio (http://localhost:8080/resources/js/demo/dispatcher_demo.js:139:18)
    at HTMLDocument.<anonymous> (http://localhost:8080/resources/js/demo/dispatcher_demo.js:198:5)
    at l (https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.3.1.min.js:2:29375)
    at c (https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.3.1.min.js:2:29677) undefined

> Error while fetching http://localhost:2000/demo/audios/1.mp3. 

i don't know if it's a CORS problem or what exactly ? 

Thanks a lot

**Comment by broofa** [comment]
You'll get this error if you try to use the sound instance before it's finished initializing (in the case of files loaded from URLs, before the HTTP request to fetch the sound file has finished loading).

Pass a callback in the Sound constructor to get notified when the sound is ready.

**Comment by numerized** [comment]
hello there, the thing that is happening to me is that this 

I don't understand, why this error shows

`[error] - Error while fetching /assets/instruments/www.bodhisattva.com/Tingsha-Ashta-Mangal-LRG.mp3.`

```
let newPizzicato = new Pizzicato.Sound(
      {
        source: 'file',
        options: { path: `/assets/instruments/${this.chosenInstruments[i].file}` },
      },
      () => {
        if (init === false) {
          newPizzicato.connect(analyser);
          setTimeout(() => {
            newPizzicato.play();
            this.lastPlayedFile = this.chosenInstruments[i].file;
          }, 10000);
        }
      },
    );
```

**Comment by broofa** [comment]
@numerized Possibly [this error](https://github.com/alemangui/pizzicato/blob/688f4d5f23a4280c19d1c517883635f4569cec57/src/Effects/Convolver.js#L63)?  If so, then the issue is the underlying XHR request failing, rather than an issue in `pizzicato`.

Maybe start by copy/pasting the URL into your browser to see if there's actually a valid resource at that path?  If that works, write a little test case to see if you can fetch the resource with XHR (outside of pizzicato).  There may be a CORS or CSP issue of some sort that's interferring with it.
