### ISSUE TITLE
Chrome 69 Release Pizzicato Library Not Functioning

### ISSUE THREAD

**Issue by christoph-phillips** [alemangui/pizzicato#91]
I started with Chrome 69 today and received this error for Pizzicato effects: 

```Uncaught DOMException: Failed to set the 'buffer' property on 'ConvolverNode': Cannot set buffer to non-null after it has been already been set to a non-null buffer
    at Pizzicato.Effects.Reverb.buildImpulse (https://alemangui.github.io/pizzicato/Pizzicato.js:1969:26)
    at Pizzicato.Effects.Reverb.set [as decay] (https://alemangui.github.io/pizzicato/Pizzicato.js:1932:30)
    at new Pizzicato.Effects.Reverb (https://alemangui.github.io/pizzicato/Pizzicato.js:1879:14)
    at https://alemangui.github.io/pizzicato/js/main.js:41:14```

I just checked the main Pizzicato demo site and same error is occurring, which prevents any audio from working on the site. Its the value setting in the `buildImpulse` function for the `reverbNode`  in the Reverb effect.

**Comment by koraysels** [comment]
I have the same problem. all other browsers seem to work..

**Comment by nascent** [comment]
Hi,

This seems to still be happening for groups.
